# Generated by Django 3.1.2 on 2020-10-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Muscles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mean', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stdev', models.DecimalField(decimal_places=2, max_digits=5)),
                ('median', models.DecimalField(decimal_places=2, max_digits=5)),
                ('variance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('label', models.BigIntegerField()),
            ],
        ),
    ]
