# Generated by Django 3.1.2 on 2020-10-20 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='muscles',
            table='muscles',
        ),
    ]
